# Generated by Django 5.1 on 2024-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_description_en_blog_description_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='surname'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='surname'),
        ),
    ]
