# Generated by Django 5.1 on 2024-09-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productcomment_email_productcomment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.productcomment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
