# Generated by Django 5.1 on 2024-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcomment_comments_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='comments',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
