# Generated by Django 5.1 on 2024-09-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_productcomment_comments_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='user',
        ),
    ]
