# Generated by Django 5.1 on 2024-10-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_description_en_product_description_uz_and_more'),
        ('shop', '0010_wishlist'),
    ]

    operations = [
    ]
