# Generated by Django 5.1 on 2024-10-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productcategory_name'),
        ('shop', '0011_merge_20241005_1914'),
    ]

    operations = [
    ]
