# Generated by Django 5.1 on 2024-10-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_merge_20241009_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
