# Generated by Django 5.1 on 2024-10-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_description_en_portfolio_description_uz_and_more'),
        ('portfolio', '0002_portfolio_details'),
    ]

    operations = [
    ]
