# Generated by Django 5.1 on 2024-10-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_merge_20241009_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
